# Number windows from 1.
set -g base-index 1

# Preserve 256-color and true-color output inside tmux.
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Tokyo Night Moon accent options.
# set -g status-style "bg=#ff757f,fg=#222436" # Red
# set -g status-style "bg=#ff966c,fg=#222436" # Orange
# set -g status-style "bg=#ffc777,fg=#222436" # Yellow
# set -g status-style "bg=#c3e88d,fg=#222436" # Green
# set -g status-style "bg=#4fd6be,fg=#222436" # Teal
# set -g status-style "bg=#86e1fc,fg=#222436" # Cyan
# set -g status-style "bg=#82aaff,fg=#222436" # Blue
# set -g status-style "bg=#fca7ea,fg=#222436" # Purple
set -g status-style "bg=#c099ff,fg=#222436" # Magenta
